camunda:
  bpm:
    database:
      type: postgres
    job-execution:
      enabled: true
      deployment-aware: true
spring:
  datasource:
    url: "jdbc:postgresql://postgresql.camunda.svc:5432/camundadb"
    username: camunda
    password: camunda
    driver-class-name: org.postgresql.Driver
